### ISSUE TITLE
Error while using the create method under Matlab R2015a

### ISSUE THREAD

**Issue by CsatiZoltan** [mdrohmann/mtocpp#1]
Could you help me what's wrong with my configuration? During calling the setup method, it writes:

[Required] Checking for doxygen...  found 1.8.10
[Required] Checking for mtoc++...  found 1.5
[Recommended] Checking for dot...  found dot - graphviz version 2.38.0 (20140413.2041)
[Recommended] Checking for latex...  found MiKTeX-pdfTeX 2.9.5700 (1.40.16) (MiKTeX 2.9 64-bit)
[Recommended] Checking for ghostscript... ghostscript not found!

So apart from Ghostscript, everything is found. After it, the create method results in:

You can now create your projects documentation by running MatlabDocMaker.create!
Starting creation of doxygen/mtoc++ powered HTML documentation for "myProj" (2.1)
Sources: C:\Users\Zoli\Desktop\2nd_approach
Output to: C:\Users\Zoli\Desktop\2nd_approach\config
Creating config files...running doxygen with mtoc++ filter...running mtoc++ postprocessor...cleaning up...done!

And after it, I get an empty documentation.

[warnings.txt](https://github.com/mdrohmann/mtocpp/files/45230/warnings.txt)

**Comment by davidvarga** [comment]
Szia!

Nem tudom hogy én miert kaptam meg ezt a levelet, viszont gyanus h a source/config mappába akar generálni.

Jo lenne latni az egeszet de mintha az output meg a config directoryk fel lennenek cserélve a setupban.

Üdv,
David

----- Eredeti üzenet -----
Feladó: "Zoltán Csáti" notifications@github.com
Feladva: ‎2015.‎11.‎26. 20:52
Címzett: "mdrohmann/mtocpp" mtocpp@noreply.github.com
Tárgy: [mtocpp] Error while using the create method under Matlab R2015a (#1)

Could you help me what's wrong with my configuration? During calling the setup method, it writes:
[Required] Checking for doxygen... found 1.8.10
[Required] Checking for mtoc++... found 1.5
[Recommended] Checking for dot... found dot - graphviz version 2.38.0 (20140413.2041)
[Recommended] Checking for latex... found MiKTeX-pdfTeX 2.9.5700 (1.40.16) (MiKTeX 2.9 64-bit)
[Recommended] Checking for ghostscript... ghostscript not found!
So apart from Ghostscript, everything is found. After it, the create method results in:
You can now create your projects documentation by running MatlabDocMaker.create!
Starting creation of doxygen/mtoc++ powered HTML documentation for "myProj" (2.1)
Sources: C:\Users\Zoli\Desktop\2nd_approach
Output to: C:\Users\Zoli\Desktop\2nd_approach\config
Creating config files...running doxygen with mtoc++ filter...running mtoc++ postprocessor...cleaning up...done!
And after it, I get an empty documentation.
warnings.txt

**Comment by CsatiZoltan** [comment]
Szervusz!

Le tudnád ellenőrizni, hogy neked működik-e? A config mappa az mtocpp programból lett átmásolva.
http://data.hu/get/9276870/2nd_approach.zip

Köszönöm előre is,
Zoltán

**Comment by davidvarga** [comment]
Szia!

Kipróbáltam. Működik. A setuppal volt gond.

_A következő lépésekkel neked is menni fog:_
1) Matlab CD a toolbox sourcera (a zip tartalmát egy mm nevű mappába
rántottam, nekem az a source, azért fogod azt látni a következőkben :) )

2) MatlabDocMaker.setup()

Do you want to keep C:\Users\vargad\Desktop\mm as your projects source
directory?
(Y)es/(N)o?:\* y*
Do you want to set C:\Users\vargad\Desktop\mm\documentation as your
documentation configuration files directory?
(Y)es/(N)o?: _n_
itt: " C:\Users\vargad\Desktop\mm\config" a válasz
Do you want to set _C:\Users\vargad\Desktop\mm\config_ as your
documentation output directory?
(Y)es/(N)o?: _n_
itt: "_C:\Users\vargad\Desktop\mm\docOut_" a válasz (nekem)

3) MatlabDocMaker.create()

Csatolom hogy nekem mit köpött ki.

Ha kell segítség szólj, én ezt a toolboxot tailoroltam egy ~1500 M-file-s
toolboxhoz, úgyhogy valószínű tudok segíteni.

Közben eszembe jutott, hogy küldtem az eredeti szerzőnek egy bugfixet, ami
fel lett tolva Git-re, azért kaptam az emailt:)

Üdv,
Dávid
1. november 27. 19:29 Zoltán Csáti írta, notifications@github.com:

**Comment by rondiplomatico** [comment]
Guys so if you want any other people to be able to help you, how about english?

**Comment by davidvarga** [comment]
Hello!

Sorry, I haven't noticed that this email-thread is basically the comment
section from GitHub.
I guess the setup from Zoltán for MatlabDocmaker is not correct therefore I
have tried it then suggested him another setup.
Maybe that helps.

David

2015-11-30 8:57 GMT+01:00 Daniel Wirtz notifications@github.com:

**Comment by CsatiZoltan** [comment]
I tried what you advised David, but it printed many warnings about this: _'D:\Programok\MATLAB' is not recognized as an internal or external command, operable program or batch file_. I attached the whole warning log. What I did was the following: I put all my files and folders into a folder named 2nd_approach. I also put two other folders there: config and docOut. The config folder contains the files from the config folder of the downloaded file mtoc++_win_1.5.zip and the mtocpp.exe and mtocpp_post.exe from the win64 folder. The MatlabDocMaker.m is put to the root of the 2nd_approach folder. Then I started the setup method, giving the 2nd_approach as my project source directory, 2nd_approach/config as the configuration directory and 2nd_approach/docOut as the documentation output directory.
My MATLAB installation path is d:\Programok\MATLAB R2015a. Can it be the problem that it contains a space? Perhaps that's why only 'D:\Programok\MATLAB' is interpreted. If that's the case, what can I do? I do not want to rename the MATLAB installation directory, because then all the links to it will be broken. How can I modify the mtocpp program so that it recognises the space in the path?

Thanks,
Zoli

[warnings.txt](https://github.com/mdrohmann/mtocpp/files/47768/warnings.txt)

**Comment by rondiplomatico** [comment]
what exactly is it you try to do with any of the sources inside your matlab installation directory? your own code should be somewhere else, and the actual location of the MatlabDocMaker script can also be anywhere.

**Comment by CsatiZoltan** [comment]
Now that I placed those folders to a path without spaces, it works well. Thanks for both of you.
The package is awesome for documenting my MATLAB programs. Will you continue maintaining this repository, to preserve compatibility with the future versions of  doxygen?

Zoli

**Comment by rondiplomatico** [comment]
hey,

great that it works out for you now.

i'll leave university soon and dont know to what extend i'll be able to do maintenance. on the verse, anyone can contribute to this repo (via the standard github fork / edit / pull request procedure), so if you feel the urgent need for doxygen updates etc feel free to do so before i get around doing it :-)
